import argparse
import json
import os
import sys
from os import path

DO_NOT_EDIT = """
/**
* ============================================
* GENERATED FILE - DO NOT EDIT MANUALLY
* ============================================
* 
* This file is automatically generated.
* Any manual changes will be overwritten.
* 
* @generated
* @fileoverview DO NOT EDIT THIS FILE
*/
"""

parser = argparse.ArgumentParser()
parser.add_argument(
    "-i",
    required=False,
    default=path.join(path.dirname(__file__), "data/curiosities.json"),
)
parser.add_argument(
    "-o",
    required=False,
    default=path.join(path.dirname(__file__), "../data.js"),
)

args = parser.parse_args()

if not os.path.exists(args.i):
    print("output file arg provided but file isnt exists", file=sys.stderr)
    sys.exit(1)

if os.path.splitext(args.i)[1] != ".json":
    print("output file arg provided but file isnt .json", file=sys.stderr)
    sys.exit(1)

if os.path.exists(args.o) and os.path.splitext(args.o)[1] != ".js":
    print("output file provided but file isnt .js", file=sys.stderr)
    sys.exit(1)


data = []

with open(args.i, "r", encoding="utf-8") as f:
    for curio in json.load(f):
        producer = None
        skills = []

        reqs = curio.get("requirements", None)
        if reqs:
            if "producer" in reqs:
                producer = reqs["producer"]["name"]

            if "skills" in reqs:
                for s in reqs["skills"]:
                    skills.append(s["name"])

        data.append(
            {
                "name": curio["name"],
                "image": curio["image"],
                "url": curio["url"],
                "points": curio["baseLP"],
                "weight": curio["mentalWeight"],
                "xpCost": curio["expCost"],
                "studySeconds": curio["studySeconds"],
                "w": curio["size"]["width"],
                "h": curio["size"]["height"],
                "producer": producer,
                "skills": skills,
            }
        )

with open(args.o, "w", encoding="utf-8") as f:
    f.write(f"{DO_NOT_EDIT}\nconst CURIOSITIES_DATA = {json.dumps(data)}\n")
